name: Push Docker Images
on:
  push:
    branches: [ main ]
env:
  IMAGE_NAME: ghcr.io/tomkerkhove/k8s-event-bridge
  IMAGE_TAG: experimental
jobs:
  push_docker_to_ghcr:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: tomkerkhove
        password: ${{ secrets.CONTAINER_REGISTRY_KEY }}
    - name: Build the Docker image
      run: docker build ./src/Kubernetes.EventBridge.Host/ --file ./src/Kubernetes.EventBridge.Host/Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    - name: Scan Docker image
      uses: azure/container-scan@v0
      with:
        image-name: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
